# Generated by Django 6.1.1 on 2026-09-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва вакансії')),
                ('company', models.CharField(max_length=255, verbose_name='Компанія')),
                ('location', models.CharField(max_length=255, verbose_name='Локація')),
                ('link', models.URLField(unique=True, verbose_name='Посилання на вакансію')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
            ],
            options={
                'verbose_name': 'Вакансія',
                'verbose_name_plural': 'Вакансії',
                'ordering': ['-created_at'],
            },
        ),
    ]
